package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1



/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private Integer ansId;
     private Admin admin;
     private Question question;
     private String ansText;
     private String ansDate;
     private String ansTime;

    public Answer() {
    }
    
          
    public Answer(Admin admin, Question question, String ansText, String ansDate, String ansTime) {
       this.admin = admin;
       this.question = question;
       this.ansText = ansText;
       this.ansDate = ansDate;
       this.ansTime = ansTime;
    }
   
    public Integer getAnsId() {
        return this.ansId;
    }
    
    public void setAnsId(Integer ansId) {
        this.ansId = ansId;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getAnsText() {
        return this.ansText;
    }
    
    public void setAnsText(String ansText) {
        this.ansText = ansText;
    }
    public String getAnsDate() {
        return this.ansDate;
    }
    
    public void setAnsDate(String ansDate) {
        this.ansDate = ansDate;
    }
    public String getAnsTime() {
        return this.ansTime;
    }
    
    public void setAnsTime(String ansTime) {
        this.ansTime = ansTime;
    }

   


}


