package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1



/**
 * BlockUser generated by hbm2java
 */
public class BlockUser  implements java.io.Serializable {


     private Integer BId;
     private Department department;
     private User user;
     private String userFname;
     private String userName;

    public BlockUser() {
    }

    public BlockUser(Department department, User user, String userFname, String userName) {
       this.department = department;
       this.user = user;
       this.userFname = userFname;
       this.userName = userName;
    }
   
    public Integer getBId() {
        return this.BId;
    }
    
    public void setBId(Integer BId) {
        this.BId = BId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUserFname() {
        return this.userFname;
    }
    
    public void setUserFname(String userFname) {
        this.userFname = userFname;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }




}


