package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private int deptId;
     private String deptName;
     private Set blockUsers = new HashSet(0);
     private Set subjects = new HashSet(0);
     private Set admins = new HashSet(0);
     private Set questions = new HashSet(0);
     private Set users = new HashSet(0);

    public Department() {
    }

    public Department(int deptId) {
        this.deptId = deptId;
    }
	
    public Department(int deptId, String deptName) {
        this.deptId = deptId;
        this.deptName = deptName;
    }
    public Department(int deptId, String deptName, Set blockUsers, Set subjects, Set admins, Set questions, Set users) {
       this.deptId = deptId;
       this.deptName = deptName;
       this.blockUsers = blockUsers;
       this.subjects = subjects;
       this.admins = admins;
       this.questions = questions;
       this.users = users;
    }
   
    public int getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(int deptId) {
        this.deptId = deptId;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    public Set getBlockUsers() {
        return this.blockUsers;
    }
    
    public void setBlockUsers(Set blockUsers) {
        this.blockUsers = blockUsers;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }
    public Set getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set admins) {
        this.admins = admins;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


