package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1



/**
 * FacultyFeedback generated by hbm2java
 */
public class FacultyFeedback  implements java.io.Serializable {


     private Integer ffId;
     private Admin admin;
     private String adminName;
     private float rating;
     private String comment;

    public FacultyFeedback() {
    }

    public FacultyFeedback(Admin admin, String adminName, float rating, String comment) {
       this.admin = admin;
       this.adminName = adminName;
       this.rating = rating;
       this.comment = comment;
    }
   
    public Integer getFfId() {
        return this.ffId;
    }
    
    public void setFfId(Integer ffId) {
        this.ffId = ffId;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public float getRating() {
        return this.rating;
    }
    
    public void setRating(float rating) {
        this.rating = rating;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


