package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private Integer FId;
     private Admin admin;
     private Question question;
     private float FScore;
     private String FComment;
     private int Score;
     private int NoOfQuestion;

    public Feedback() {
    }

    public Feedback(Admin admin, Question question, float FScore, String FComment) {
       this.admin = admin;
       this.question = question;
       this.FScore = FScore;
       this.FComment = FComment;
    }
 
    public int getScore() {
        return this.Score;
    }
    
    public void setScore(int Score) {
        this.Score = Score;
    }
    
    public int getNoOfQuestion() {
        return this.NoOfQuestion;
    }
    
    public void setNoOfQuestion(int NoOfQuestion) {
        this.NoOfQuestion = NoOfQuestion;
    }
 
    public Integer getFId() {
        return this.FId;
    }
    
    public void setFId(Integer FId) {
        this.FId = FId;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public float getFScore() {
        return this.FScore;
    }
    
    public void setFScore(float FScore) {
        this.FScore = FScore;
    }
    public String getFComment() {
        return this.FComment;
    }
    
    public void setFComment(String FComment) {
        this.FComment = FComment;
    }




}


