package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer queId;
     private Department department;
     private Subject subject;
     private User user;
     private String queText;
     private String queDate;
     private String queTime;
     private String queStatus;
     private Set answers = new HashSet(0);
     private Set feedbacks = new HashSet(0);

    public Question() {
    }
    
    public Question(int queId) {
        this.queId = queId;
    }

    public Question(Department department, Subject subject, User user, String queText, String queDate, String queTime, String queStatus) {
        this.department = department;
        this.subject = subject;
        this.user = user;
        this.queText = queText;
        this.queDate = queDate;
        this.queTime = queTime;
        this.queStatus = queStatus;
    }
    public Question(Department department, Subject subject, User user, String queText, String queDate, String queTime, String queStatus, Set answers, Set feedbacks) {
       this.department = department;
       this.subject = subject;
       this.user = user;
       this.queText = queText;
       this.queDate = queDate;
       this.queTime = queTime;
       this.queStatus = queStatus;
       this.answers = answers;
       this.feedbacks = feedbacks;
    }
   
    public Integer getQueId() {
        return this.queId;
    }
    
    public void setQueId(Integer queId) {
        this.queId = queId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getQueText() {
        return this.queText;
    }
    
    public void setQueText(String queText) {
        this.queText = queText;
    }
    public String getQueDate() {
        return this.queDate;
    }
    
    public void setQueDate(String queDate) {
        this.queDate = queDate;
    }
    public String getQueTime() {
        return this.queTime;
    }
    
    public void setQueTime(String queTime) {
        this.queTime = queTime;
    }
    public String getQueStatus() {
        return this.queStatus;
    }
    
    public void setQueStatus(String queStatus) {
        this.queStatus = queStatus;
    }
    public Set getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set answers) {
        this.answers = answers;
    }
    public Set getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set feedbacks) {
        this.feedbacks = feedbacks;
    }




}


