package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private Integer subId;
     private Department department;
     private String subName;
     private Set admins = new HashSet(0);
     private Set questions = new HashSet(0);

    public Subject() {
    }
    
    public Subject(int subId){
        this.subId = subId;
    }
    public Subject(Department department, String subName) {
        this.department = department;
        this.subName = subName;
    }
    public Subject(Department department, String subName, Set admins, Set questions) {
       this.department = department;
       this.subName = subName;
       this.admins = admins;
       this.questions = questions;
    }
   
    public Integer getSubId() {
        return this.subId;
    }
    
    public void setSubId(Integer subId) {
        this.subId = subId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getSubName() {
        return this.subName;
    }
    
    public void setSubName(String subName) {
        this.subName = subName;
    }
    public Set getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set admins) {
        this.admins = admins;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


