package Tables;
// Generated Apr 9, 2020 1:59:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private Department department;
     private String userFname;
     private String userName;
     private String userPwd;
     private String userType;
     private String userEmail;
     private Set blockUsers = new HashSet(0);
     private Set questions = new HashSet(0);

    public User() {
    }
    
    public User(int userId) {
        this.userId = userId;
    }
	
    public User(Department department, String userFname, String userName, String userPwd, String userType, String userEmail) {
        this.department = department;
        this.userFname = userFname;
        this.userName = userName;
        this.userPwd = userPwd;
        this.userType = userType;
        this.userEmail = userEmail;
    }
    public User(Department department, String userFname, String userName, String userPwd, String userType, String userEmail, Set blockUsers, Set questions) {
       this.department = department;
       this.userFname = userFname;
       this.userName = userName;
       this.userPwd = userPwd;
       this.userType = userType;
       this.userEmail = userEmail;
       this.blockUsers = blockUsers;
       this.questions = questions;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getUserFname() {
        return this.userFname;
    }
    
    public void setUserFname(String userFname) {
        this.userFname = userFname;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Set getBlockUsers() {
        return this.blockUsers;
    }
    
    public void setBlockUsers(Set blockUsers) {
        this.blockUsers = blockUsers;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


